#!/usr/bin/env python3
"""Regenerate the Codex agent and prompt files from the plugin's own sources.

`agents/*.md` and `commands/*.md` are the single source of truth. Codex cannot
read either — its plugin manifest accepts `skills` and nothing else — so the
same content is projected into the two shapes Codex *does* read:

    agents/<name>.md   ->  codex/agents/<name>.toml    (custom agent)
    commands/<name>.md ->  codex/prompts/<name>.md     (custom prompt)

Run this after editing anything under agents/ or commands/, and commit the
result. Drift here is silent — the Codex copy simply teaches an older rule —
so the check belongs in the same change as the edit.

    python3 codex/sync-from-plugin.py            # write
    python3 codex/sync-from-plugin.py --check    # fail if out of date (CI-shaped)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
AGENTS_SRC = REPO / "agents"
COMMANDS_SRC = REPO / "commands"
AGENTS_OUT = REPO / "codex" / "agents"
PROMPTS_OUT = REPO / "codex" / "prompts"

GENERATED = "# GENERATED by codex/sync-from-plugin.py — edit {src}, then re-run.\n"

# Read-only reviewers must not be able to write. The two testers run the suite.
SANDBOX = {
    "dotnet-code-reviewer": "read-only",
    "dotnet-architecture-reviewer": "read-only",
    "dotnet-security-reviewer": "read-only",
    "dotnet-performance-reviewer": "read-only",
    "dotnet-unit-tester": "workspace-write",
    "dotnet-integration-tester": "workspace-write",
}

HARNESS_NOTE = """## Harness note — you are running as a Codex subagent

This agent is a projection of the `dotnet-standards` plugin's own agent
definition. Two adjustments, and nothing else changes:

- Where the body says "load X with the Skill tool", load the skill however this
  harness loads skills. If it has no skill tool, read the plugin's
  `skills/<name>/SKILL.md` directly. **Loading it is not optional** — the rubric
  owns the method, and reviewing from memory of it is the failure this agent
  exists to prevent.
- Return your report as your final message. You cannot write files, and the
  session that spawned you assembles the reports.

"""


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---", 4)
    if end == -1:
        return "", text
    return text[4:end], text[end + 4 :].lstrip("\n")


def frontmatter_field(front: str, key: str) -> str:
    """Minimal reader for the two shapes these files use: `k: v` and `k: >-`."""
    lines = front.splitlines()
    for i, line in enumerate(lines):
        if not line.startswith(key + ":"):
            continue
        rest = line[len(key) + 1 :].strip()
        if rest and rest not in (">-", ">", "|", "|-"):
            return rest.strip("\"'")
        block = []
        for follow in lines[i + 1 :]:
            if follow and not follow.startswith(("  ", "\t")):
                break
            block.append(follow.strip())
        return " ".join(part for part in block if part)
    return ""


def toml_literal(value: str) -> str:
    """A TOML multi-line literal string: no escape processing, so Windows paths
    and regexes in the body survive intact. Guard the one sequence that cannot
    appear inside one."""
    if "'''" in value:
        raise SystemExit("agent body contains ''' — cannot emit a TOML literal string")
    return "'''\n" + value.rstrip() + "\n'''"


def build_agent(path: Path) -> tuple[Path, str]:
    front, body = split_frontmatter(path.read_text(encoding="utf-8"))
    name = frontmatter_field(front, "name") or path.stem
    description = frontmatter_field(front, "description")
    if not description:
        raise SystemExit(f"{path.name}: no description in frontmatter")
    sandbox = SANDBOX.get(name)
    if sandbox is None:
        raise SystemExit(f"{path.name}: add {name} to SANDBOX before shipping it")

    out = [GENERATED.format(src=f"agents/{path.name}")]
    out.append(f"name = {name!r}".replace("'", '"'))
    out.append(f"description = {description!r}".replace("'", '"'))
    out.append(f'sandbox_mode = "{sandbox}"')
    out.append("model_reasoning_effort = \"high\"")
    out.append("developer_instructions = " + toml_literal(HARNESS_NOTE + body))
    return AGENTS_OUT / f"{name}.toml", "\n".join(out) + "\n"


def build_prompt(path: Path) -> tuple[Path, str]:
    front, body = split_frontmatter(path.read_text(encoding="utf-8"))
    description = frontmatter_field(front, "description")
    hint = frontmatter_field(front, "argument-hint")
    head = ["---", f"description: {description}"]
    if hint:
        head.append(f"argument-hint: {hint}")
    head.append("---")
    head.append("")
    head.append(
        "<!-- GENERATED by codex/sync-from-plugin.py — edit "
        f"commands/{path.name}, then re-run. -->"
    )
    head.append("")
    return PROMPTS_OUT / path.name, "\n".join(head) + "\n" + body.rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    AGENTS_OUT.mkdir(parents=True, exist_ok=True)
    PROMPTS_OUT.mkdir(parents=True, exist_ok=True)

    planned: list[tuple[Path, str]] = []
    planned += [build_agent(p) for p in sorted(AGENTS_SRC.glob("*.md"))]
    planned += [build_prompt(p) for p in sorted(COMMANDS_SRC.glob("*.md"))]

    stale = []
    for target, content in planned:
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == content:
            continue
        stale.append(target.relative_to(REPO).as_posix())
        if not args.check:
            target.write_text(content, encoding="utf-8", newline="\n")

    if args.check:
        if stale:
            print("Codex projections are out of date:")
            for name in stale:
                print(f"- {name}")
            return 1
        print(f"Codex projections up to date ({len(planned)} files).")
        return 0

    print(f"Wrote {len(stale)} of {len(planned)} files.")
    for name in stale:
        print(f"- {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
